name: Megan Royle MUA
favicon: null
layout_spectrum: 0.1813072646036744
typography_spectrum: 0.2238230963703245
title: Makeup and Hair Artist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#6a6a6a'
    - '#323232'
    - '#b5b5b5'
    - '#efefef'
  brandStrength: 0.8388354543130845
  lightness: 0.8460401599295437
  saturation: 0.9012127057649195
  rhythmicContrast: 0.75
purpose: []
